language: java
jdk:
  - openjdk17

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - lew0205@naver.com

before_deploy:
  - zip -r jojoldu-book-tuto *
  - mkdir -p deploy
  - mv jojoldu-book-tuto.zip deploy/jojoldu-book-tuto.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: holu-jojoldu-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: holu-jojoldu-build
    key: jojoldu-book-tuto.zip

    bundle_type: zip
    application: holu-jojoldu-service
    deployment_group: holu-jojoldu-service-group
    region: ap-northeast-2
    wait-until-deployed: true