spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1001384515663-opo53qt85ti22f9umuf5a3fafmpevb30.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
#            client-authentication-method: post